M48
; DRILL file {KiCad 9.0.2} date 2025-06-16T21:06:24+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-16T21:06:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X50.96Y-80.825
X56.74Y-80.825
T2
X16.6Y-77.4
X16.6Y-176.6
X122.5Y-77.4
X122.5Y-176.6
M30
